### PR TITLE
Cache git-repo-version

### PR DESCRIPTION
**Pull request by stefanpenner**

### CODE REVIEW

**Comment by stefanpenner** [comment]
cc @krisselden one idea

**Comment by stefanpenner** [comment]
cc @EmberSherpa as this is included by default in ember-cli's blueprint, is it possible for some of the ember-cli core team members to get commit/publish on it. That way we can reduce the buss-factory, and also not need to bug you when you are busy :)

**Comment by taras** [comment]
@stefanpenner I added you, @rwjblue and @locks as contributors. 

I can add someone to npm as well. Who would like?

**Comment by rwjblue** [comment]
Stef and I would be good for NPM. We would likely set it up for automated publishing like we have for other repos.

**Comment by stefanpenner** [comment]
@taras awesome thanks! We can help you maintain

**Comment by rwjblue** [comment]
closing this for now, I believe that @krisselden resolved via config caching in ember-cli itself

**Pull request closed without merging**
