### PR TITLE
Whitelist in package.json only required files

### PR DESCRIPTION
**Pull request by cibernox**
Part of the quest to reduce the number of files of ember-cli: https://github.com/ember-cli/ember-cli/issues/6147

### CODE REVIEW

**Comment by jonkoops** [comment]
Your pull request is removing some .gitkeep files but they are already ignored in .npmingnore

**Comment by Turbo87** [comment]
@cibernox as @jonkoops mentioned already the npmignore file is no longer necessary if we have the files key in package.json

**Comment by jonkoops** [comment]
@Turbo87 Actually, I am advocating keeping the .gitkeep and .npmignore around. As the NPM documentation states:

> The "files" field is an array of files to include in your project. If you name a folder in the array, then it will also include the files inside that folder. (Unless they would be ignored by another rule.)

> You can also provide a ".npmignore" file in the root of your package or in subdirectories, which will keep files from being included, **even if they would be picked up by the files array**. The .npmignore file works just like a .gitignore.

We could remove 80% of the contents of the .npmignore file since they are paths that are no longer relevant due to the files specified in package.json. However we should still use .npmignore to ignore certain files that do exists within the paths specified by files (like .gitkeep).

**Comment by Turbo87** [comment]
@jonkoops what's the point of having those files at all?

**Comment by taras** [comment]
This looks good to me!

**Comment by jonkoops** [comment]
@Turbo87 It's more for when new .gitkeep (or other) files are introduced for some reason in the future. I guess it's probably unnecessary for this specific package but it might be more relevant as a default for addons generated by Ember CLI since they will include these files by default.

**Comment by jonkoops** [comment]
@taras You could probably remove .npmignore from the project, since it has no added value after merging this pull request.

**Pull request merged**
