### PR TITLE
Configurable version override

### PR DESCRIPTION
**Pull request by mirague**
Addresses #41

### CODE REVIEW

**Comment by mirague** [comment]
@taras It seems the `config` var passed into the `config()` method is empty `{}` (as discussed on #41). I could access the config through `baseConfig` though so that's what I've done.

**Comment by simonihmig** [comment]
Would love to have this available! 👍

**Comment by mirague** [comment]
Still waiting for a review and merge!

**Comment by simonihmig** [comment]
@taras ping :)

**Comment by jtgeibel** [comment]
I'm interested in this as well.  I went to add this to crates.io when I noticed that we're already using it but the hash isn't being picked up in production on Heroku.

**Pull request merged**
