### PR TITLE
upgrade git-repo-version

### PR DESCRIPTION
**Pull request by BryanCrotaz**
Fixes issue #54

### CODE REVIEW

**Comment by locks** [comment]
CI is failing on account of the new `git-repo-version` version needing node 6+: https://travis-ci.org/EmberSherpa/ember-cli-app-version/jobs/306123493#L532.

**Comment by stefanpenner** [comment]
released as v3.1.1 🎉

**Comment by BryanCrotaz** [comment]
Ta muchly

**Comment by rwjblue** [comment]
FYI - `git-repo-version@1.0.0` updated `engines` to require `>= 6`, which is breaking ember-cli CI. 

I believe that @cibernox is fixing forward though...

**Comment by cibernox** [comment]
I released 1.0.1 with compatibility for node 4+. It was already compatible really, I just made it explicit in the package.json.

**Pull request merged**
